// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3taltoJPoj5NPlWZjqxj21BFPM85reB0',
    appId: '1:646868314806:web:513aab0b160cd0e0859417',
    messagingSenderId: '646868314806',
    projectId: 'objectdetection-a5557',
    authDomain: 'objectdetection-a5557.firebaseapp.com',
    databaseURL: 'https://objectdetection-a5557-default-rtdb.firebaseio.com',
    storageBucket: 'objectdetection-a5557.firebasestorage.app',
    measurementId: 'G-BN7MD1DKKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf9xG8q8WhDLEotL15xhwcrS9E9BcfzpQ',
    appId: '1:646868314806:android:45494161b32a9879859417',
    messagingSenderId: '646868314806',
    projectId: 'objectdetection-a5557',
    databaseURL: 'https://objectdetection-a5557-default-rtdb.firebaseio.com',
    storageBucket: 'objectdetection-a5557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Fr4mtja3LEHRK75V8vU7AUG1boWBbOE',
    appId: '1:646868314806:ios:091b6c09dcd32a4b859417',
    messagingSenderId: '646868314806',
    projectId: 'objectdetection-a5557',
    databaseURL: 'https://objectdetection-a5557-default-rtdb.firebaseio.com',
    storageBucket: 'objectdetection-a5557.firebasestorage.app',
    iosBundleId: 'com.example.blindStickWithTtsEspcam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Fr4mtja3LEHRK75V8vU7AUG1boWBbOE',
    appId: '1:646868314806:ios:091b6c09dcd32a4b859417',
    messagingSenderId: '646868314806',
    projectId: 'objectdetection-a5557',
    databaseURL: 'https://objectdetection-a5557-default-rtdb.firebaseio.com',
    storageBucket: 'objectdetection-a5557.firebasestorage.app',
    iosBundleId: 'com.example.blindStickWithTtsEspcam',
  );
}
